### ISSUE TITLE
[Feature] Tabs

### ISSUE THREAD

**Issue by ellisgl** [vinibiavatti1/TuiCss#1]
TUI Tabs would be a nice feature to have. See http://seiyria.com/dos-strap/components/#nav for an example.

**Comment by vinibiavatti1** [comment]
Hi ellisgl. Thanks for your feature idea. I have already created this, and its is available in the project. There is an example of tabs component in the BIOS example file. Please, access the wiki and enter in the examples page. The first example has this feature. If you want to check the code, you can find it in the `examples/bios.html`. I'm updating the documentation, and i'm moving it to the wiki. The README.md is out of date, so, when I created the tabs docs, I'll write it to u here. Thanks!!

**Comment by vinibiavatti1** [comment]
This issue will be closed when the docs were provided.

**Comment by vinibiavatti1** [comment]
This is available in the v1.0.0 release.
