### ISSUE TITLE
Navbar links not working on mobile

### ISSUE THREAD

**Issue by otrsw** [vinibiavatti1/TuiCss#28]
Firstly - thank you for developing this great library!  Really love the styling.
I have a question about the navbar links - all works perfectly on desktop, and even when testing with developer tools to see the responsive layout.
However, when I test the live site from my phone, the nav links do not work when clicked?

If you want to test - you may log in to: https://www.retro-apps.online/

Username: test@test.com
Password: test12345

Thank you.

**Comment by vinibiavatti1** [comment]
I've to thank you for using my lib! I entered your application and like too much. I will register myself there to check the situation, and evaluate this to fix in the next feature of the lib. Count on me.

**Comment by vinibiavatti1** [comment]
Hi @otrsw, I updated the lib with some fixes. I discovered that the media queries were not being imported in the build process. I fixed this and now, you can control when the elements will appear depending the device screen size. Please, update the dependency of tuicss to v2.1.1 and test again. If the problem still continues, please, commet here ;)

Note: I created an account in your application. Sorry! I saw just now you shared a test acount. But anyway, congratulations for the development of the application. I'm so glad!
