### ISSUE TITLE
Proposal of showcase project - Stellar Duel

### ISSUE THREAD

**Issue by deleterium** [vinibiavatti1/TuiCss#36]
> Showcase proposal template
> Note: "*" fields are mandatory.

> Project Name: The name of the project that will be used as title of the section of the showcase. 

Project Name *:  Stellar Duel

> Project Description: The description of the project that will be used as a paragraph after the title of the showcase.

Project Description *: The game is a smart contracts on Signum blockchain. Players can choose a fleet and fight each others. The web page connects the players and the smart contract, making transactions much easier.

> Project Author: The author of the project that will be informed after the project description. (Keep if blank to don't show the author)

Project Author: Rui Deleterium

> Project Links: Links to access the project showcase. These links will be shown after project description.

Project Links: https://stellarduel.space/

> Project Images: Images of the project (can be the images with legends, or the links to it).

Project Images *:
https://user-images.githubusercontent.com/54009773/170266796-5aa8c548-5403-4a93-b98e-a1e8c8a1b185.png
https://user-images.githubusercontent.com/54009773/170266813-91f8e119-509e-4669-a1f6-7a0a34821d97.png
https://user-images.githubusercontent.com/54009773/170266826-ca15d811-1f99-40d8-97af-8589ab8722cb.png

> Additional Information: Other relevant information.

Additional Information: TuiCSS was a great fit for this project that aimed to be a very simple game to remember the beginning of multiplayer games on the internet during the late 80's.

> Feedback: If you want to give a feedback to the project, or a suggestion, please, enjoy this field!

Feedback: Some measures are different when rendering is on mobile or desktop. I tweaked some to be always in 'ch' units. Probably changing most of them to 'ch' would make the design consistent between mobile and desktop.

**Comment by vinibiavatti1** [comment]
Thanks! I will open a new issue about your feedback and check the best solution for it in the next releases. Please, just check the showcase page if you liked the way I put the content there. If you have some suggestion, or wants to change something there, say here ;).
