### ISSUE TITLE
Desculpa abrir uma issue fora do escopo do projeto, mas estou curioso

### ISSUE THREAD

**Issue by filipedeschamps** [vinibiavatti1/TuiCss#39]
@vinibiavatti1 tudo bem? Eu devo estar quebrando alguma regra de contribuição do repositório ao abrir essa issue, mas fiquei muito curioso com algo.

Eu acabei de fazer [essa publicação no TabNews](https://www.tabnews.com.br/filipedeschamps/frameworks-css-com-estilos-unicos-que-simulam-desenho-a-mao-video-games-sistemas-operacionais-tela-de-terminal) sobre Frameworks CSS e listei este seu framework. Para ilustrar a publicação, usei a foto que está no README, mas só agora percebi que os dados preenchidos ali são **Blumenau**, **Santa Catarina**... você é de Blumenau? Eu também sou 😍

**Comment by vinibiavatti1** [comment]
Eai @filipedeschamps, tudo certo sim, e contigo? Pode ficar tranquilo, não existem regras não XD. 

É um grande prazer receber essa mensagem! Primeiramente pela coincidência de eu ter descoberto seu canal algumas semanas atrás, e por saber que você também é de Blumenau. Quem sabe algum dia já te vi lá e mal podia imaginar que este rapaz seria um grande no Youtube, com paixão por programação. Fico muito contente pelo seu trabalho, e pela publicação que fizeste sobre este projecto. Valeu mesmo por ter escolhido o TuiCss na lista. 

Vou te mandar uma mensagem pelo instagram, e assim conversamos sobre qualquer coisa quando puder, pode ser?
Nota: Ganhou mais um inscrito :D

**Comment by filipedeschamps** [comment]
> Valeu mesmo por ter escolhido o TuiCss na lista.

De todos da lista, o que mais gostei foi o TuiCss 😍 muitas saudades dessa época. Eu usava em Blumenau um software de gestão de estoque chamado Planejo que era 100% assim!

> Vou te mandar uma mensagem pelo instagram, e assim conversamos sobre qualquer coisa quando puder, pode ser?
Nota: Ganhou mais um inscrito :D

Valeu pela inscrição 🤝 👍  sobre o Insta, desinstalei ele do meu celular e quem toca é o meu irmão. Hoje o melhor lugar para me encontrar é no TabNews mesmo 😂  o repositório está privado, mas se quiser que envie o convite me avise 🤝 

Abração meu caro! To fechado a issue e muito obrigado por responder ela 🎉
