### ISSUE TITLE
wiki: add links to github page version of example to example wiki page

### ISSUE THREAD

**Issue by barakplasma** [vinibiavatti1/TuiCss#43]
I noticed that all the examples are hosted already at urls like https://vinibiavatti1.github.io/TuiCss/examples/progress-bar.html
I'd like to add links to the github page version of the examples to the example wiki page.

This is what it could look like:
### Progress Bars - [Demo](https://vinibiavatti1.github.io/TuiCss/examples/progress-bar.html)
This is a demo of some kind of progress bars in the framework. Acess the page [[Progressbar]] to check about it.

**Comment by brettwilcox** [comment]
I noticed the same and would also like links to the example pages. It would also be helpful to have an index with the ability to browse from one example to the next.

**Comment by vinibiavatti1** [comment]
Hello!

Sorry for seeing it too late, anyway, I liked your suggestions and added the links to the demo pages in the "Examples" wiki page. Can you check there if it is what you expect?

Thanks a lot!

**Comment by barakplasma** [comment]
https://github.com/vinibiavatti1/TuiCss/wiki/Examples looks great!
