### ISSUE TITLE
 TuiCss use / maintanence?

### ISSUE THREAD

**Issue by 8bitsten** [vinibiavatti1/TuiCss#46]
Hello,

Is it still actively developed (maybe dome fork?)? I have started using it, but the project seems to be abandoned, no new examples and/or components were added for a longer time.

Thanks a lot
Petr

**Comment by vinibiavatti1** [comment]
Hi

I'm just working on bug fixes and accepting new suggestions. Be free to contribute. I don't have any plans on this project for the next times. Thanks!
